/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mqttjava;

import java.io.IOException;

import org.eclipse.paho.client.mqttv3.MqttClient;
import org.eclipse.paho.client.mqttv3.MqttConnectOptions;
import org.eclipse.paho.client.mqttv3.MqttException;
import org.eclipse.paho.client.mqttv3.persist.MemoryPersistence;

public class App {

    private static String hostname = "localhost";

    public static void main(String[] args) {
        if (args.length > 0) {
            hostname = args[0];
        }

        System.out.println("Starting...");

        String broker = String.format("tcp://%s:1883", hostname);
        String clientId = "MqttJava";
        MemoryPersistence persistence = new MemoryPersistence();

        try {
            MqttClient client = new MqttClient(broker, clientId, persistence);
            MqttConnectOptions connOpts = new MqttConnectOptions();
            connOpts.setCleanSession(true);
            System.out.println("Connecting to broker: " + broker);
            System.out.println(String.format("Try to connect to %s on port 1883 ...", hostname));
            client.connect(connOpts);
            client.setCallback(new Callback());
            System.out.println("Connected");
            client.subscribe("temperature/+");
            System.in.read();

        } catch (MqttException me) {
            me.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
